import { Square, Circle, Triangle, Diamond, Pentagon, Octagon, Star } from 'lucide-react';
import React from 'react';
// @ts-ignore
import pirateImg from './assets/images/pirate_island_quest_map_1779210700182.png';

export const ASSETS = {
  STAGES: [
    { name: 'Letter A', src: 'https://img.icons8.com/?size=100&id=5lilTZK2iMKH&format=png&color=000000', type: 'stage', subType: 'letter-a' },
    { name: 'Letter B', src: 'https://img.icons8.com/?size=100&id=N1yiSYwBoiTT&format=png&color=000000', type: 'stage', subType: 'letter-b' },
    { name: 'Letter C', src: 'https://img.icons8.com/?size=100&id=QB5QJEXybCmE&format=png&color=000000', type: 'stage', subType: 'letter-c' },
    { name: 'Letter D', src: 'https://img.icons8.com/?size=100&id=605jYmYaCPZO&format=png&color=000000', type: 'stage', subType: 'letter-d' },
    { name: 'Letter E', src: 'https://img.icons8.com/?size=100&id=GoRYWiFqKWkc&format=png&color=000000', type: 'stage', subType: 'letter-e' },
    { name: 'Letter F', src: 'https://img.icons8.com/?size=100&id=Ek1c7AmZmimj&format=png&color=000000', type: 'stage', subType: 'letter-f' },
    { name: 'Letter G', src: 'https://img.icons8.com/?size=100&id=oeuHHn12W4Ak&format=png&color=000000', type: 'stage', subType: 'letter-g' },
    { name: 'Letter H', src: 'https://img.icons8.com/?size=100&id=ZDHv0f0DgqlY&format=png&color=000000', type: 'stage', subType: 'letter-h' },
    { name: 'Letter I', src: 'https://img.icons8.com/?size=100&id=WpKkggxKrsg9&format=png&color=000000', type: 'stage', subType: 'letter-i' },
    { name: 'Letter J', src: 'https://img.icons8.com/?size=100&id=coyLt1Hzt7K9&format=png&color=000000', type: 'stage', subType: 'letter-j' },
    { name: 'Letter K', src: 'https://img.icons8.com/?size=100&id=YWUtEcpzOdrF&format=png&color=000000', type: 'stage', subType: 'letter-k' },
    { name: 'Letter L', src: 'https://img.icons8.com/?size=100&id=s0XMC6wylOH0&format=png&color=000000', type: 'stage', subType: 'letter-l' },
    { name: 'Letter M', src: 'https://img.icons8.com/?size=100&id=vl7tZspv3Ny6&format=png&color=000000', type: 'stage', subType: 'letter-m' },
    { name: 'Letter N', src: 'https://img.icons8.com/?size=100&id=KSJHTirvkhTf&format=png&color=000000', type: 'stage', subType: 'letter-n' },
    { name: 'Letter O', src: 'https://img.icons8.com/?size=100&id=qqZygLMeQWHD&format=png&color=000000', type: 'stage', subType: 'letter-o' },
    { name: 'Letter P', src: 'https://img.icons8.com/?size=100&id=ovME8tgb59Pq&format=png&color=000000', type: 'stage', subType: 'letter-p' },
    { name: 'Letter Q', src: 'https://img.icons8.com/?size=100&id=ObWk2eGQU678&format=png&color=000000', type: 'stage', subType: 'letter-q' },
    { name: 'Letter R', src: 'https://img.icons8.com/?size=100&id=mSpyyubrjSWs&format=png&color=000000', type: 'stage', subType: 'letter-r' },
    { name: 'Letter S', src: 'https://img.icons8.com/?size=100&id=lQKUQQfJ4cBV&format=png&color=000000', type: 'stage', subType: 'letter-s' },
    { name: 'Letter T', src: 'https://img.icons8.com/?size=100&id=BTNAqD2IIXSp&format=png&color=000000', type: 'stage', subType: 'letter-t' },
    { name: 'Letter U', src: 'https://img.icons8.com/?size=100&id=QrWbEQx0JkFM&format=png&color=000000', type: 'stage', subType: 'letter-u' },
    { name: 'Letter V', src: 'https://img.icons8.com/?size=100&id=vFDt9RHk9gBZ&format=png&color=000000', type: 'stage', subType: 'letter-v' },
    { name: 'Letter W', src: 'https://img.icons8.com/?size=100&id=WCLynHWWABcH&format=png&color=000000', type: 'stage', subType: 'letter-w' },
    { name: 'Letter X', src: 'https://img.icons8.com/?size=100&id=I02TdaPxbwRz&format=png&color=000000', type: 'stage', subType: 'letter-x' },
    { name: 'Letter Y', src: 'https://img.icons8.com/?size=100&id=Ifn8lNyUdhKk&format=png&color=000000', type: 'stage', subType: 'letter-y' },
    { name: 'Letter Z', src: 'https://img.icons8.com/?size=100&id=gMefh70z97v7&format=png&color=000000', type: 'stage', subType: 'letter-z' },
    { name: 'Number 1', src: 'https://img.icons8.com/?size=100&id=5gi5Fhj344Ay&format=png&color=000000', type: 'stage', subType: 'number-1' },
    { name: 'Number 2', src: 'https://img.icons8.com/?size=100&id=zfXniQqU2x6w&format=png&color=000000', type: 'stage', subType: 'number-2' },
    { name: 'Number 3', src: 'https://img.icons8.com/?size=100&id=LwdHuTXSHOOG&format=png&color=000000', type: 'stage', subType: 'number-3' },
    { name: 'Number 4', src: 'https://img.icons8.com/?size=100&id=Gk42Os2sofSY&format=png&color=000000', type: 'stage', subType: 'number-4' },
    { name: 'Number 5', src: 'https://img.icons8.com/?size=100&id=7eDIImJNz6OM&format=png&color=000000', type: 'stage', subType: 'number-5' },
    { name: 'Number 6', src: 'https://img.icons8.com/?size=100&id=sBteeVAWVWdN&format=png&color=000000', type: 'stage', subType: 'number-6' },
    { name: 'Number 7', src: 'https://img.icons8.com/?size=100&id=fQvhDtbvc6bG&format=png&color=000000', type: 'stage', subType: 'number-7' },
    { name: 'Number 8', src: 'https://img.icons8.com/?size=100&id=idTiKYYUOlBM&format=png&color=000000', type: 'stage', subType: 'number-8' },
    { name: 'Number 9', src: 'https://img.icons8.com/?size=100&id=9v54DxjxtjdV&format=png&color=000000', type: 'stage', subType: 'number-9' },
    { name: 'Number 0', src: 'https://img.icons8.com/?size=100&id=TASMsNez3JUr&format=png&color=000000', type: 'stage', subType: 'number-0' },
    { name: 'Monkey', src: 'https://img.icons8.com/?size=100&id=BZO3S6QnAZkQ&format=png&color=000000', type: 'stage', subType: 'monkey' },
    { name: 'The King', src: 'https://img.icons8.com/color/512/king.png', type: 'stage', subType: 'king' },
    { name: 'Treasure Chest', src: 'https://img.icons8.com/color/512/treasure-chest.png', type: 'stage', subType: 'chest' },
    { name: 'Golden Coin', src: 'https://img.icons8.com/color/512/coins.png', type: 'stage', subType: 'coin' },
    { name: 'Royal Guard', src: 'https://img.icons8.com/?size=100&id=FJx1UsEw8Og5&format=png&color=000000', type: 'stage', subType: 'guard' },
    { name: 'Prison', src: 'https://img.icons8.com/?size=100&id=40215&format=png&color=000000', type: 'stage', subType: 'prison' },
    { name: 'Jousting Knight', src: 'https://img.icons8.com/color/512/knight.png', type: 'stage', subType: 'knight_joust' },
    { name: 'Golden Lion', src: 'https://img.icons8.com/?size=100&id=zHfPqyoBsDs8&format=png&color=000000', type: 'stage', subType: 'lion' },
    { name: 'Titan Elephant', src: 'https://img.icons8.com/color/512/elephant.png', type: 'stage', subType: 'elephant' },
    { name: 'Noble Steed', src: 'https://img.icons8.com/color/512/horseback-riding.png', type: 'stage', subType: 'rider' },
    { name: 'Summit Flag', src: 'https://img.icons8.com/color/512/mountain.png', type: 'stage', subType: 'peak' },
    { name: 'Waypoint Pin', src: 'https://img.icons8.com/color/512/marker.png', type: 'stage', subType: 'pin' },
    { name: 'Bike', src: 'https://img.icons8.com/?size=100&id=80394&format=png&color=000000', type: 'stage', subType: 'bike' },
    { name: 'Car', src: 'https://img.icons8.com/?size=100&id=iCc4Jhkr6cRU&format=png&color=000000', type: 'stage', subType: 'car' },
    { name: 'Truck', src: 'https://img.icons8.com/?size=100&id=JLdAnWscYCuC&format=png&color=000000', type: 'stage', subType: 'truck' },
    { name: 'Cow', src: 'https://img.icons8.com/?size=100&id=yKzfvDUQi1fO&format=png&color=000000', type: 'stage', subType: 'cow' },
    { name: 'Horse', src: 'https://img.icons8.com/?size=100&id=0YPxCqgQKTtL&format=png&color=000000', type: 'stage', subType: 'Horse' },

    { name: 'Sheep', src: 'https://img.icons8.com/?size=100&id=oUEefTUhhoQo&format=png&color=000000', type: 'stage', subType: 'sheep' },
    { name: 'Brown Rooster', src: 'https://img.icons8.com/?size=100&id=101707&format=png&color=000000', type: 'stage', subType: 'rooster' },
    { name: 'Hen', src: 'https://img.icons8.com/?size=100&id=klPznVmtY4DD&format=png&color=000000', type: 'stage', subType: 'hen' },
    { name: 'Duck', src: 'https://img.icons8.com/?size=100&id=Tjycw5Lntbk1&format=png&color=000000', type: 'stage', subType: 'duck' },
    { name: 'Bird', src: 'https://img.icons8.com/?size=100&id=101704&format=png&color=000000', type: 'stage', subType: 'bird' },
    { name: 'Ghost Tree', src: 'https://img.icons8.com/?size=100&id=fbBIGkfpYM9S&format=png&color=000000', type: 'stage', subType: 'ghost_tree' },
    { name: 'Banana Tree', src: 'https://img.icons8.com/?size=100&id=LRV2NrJaGC5w&format=png&color=000000', type: 'stage', subType: 'Banana Tree' },
    { name: 'Tree-2', src: 'https://img.icons8.com/?size=100&id=5FWNILzuBe9p&format=png&color=000000', type: 'stage', subType: 'tree2' },
    { name: 'Growing Plant', src: 'https://img.icons8.com/?size=100&id=bocbBHYM4FYd&format=png&color=000000', type: 'stage', subType: 'Growing Plant' },
    { name: 'Huge Tree', src: 'https://img.icons8.com/?size=100&id=Dwvqs66BIWjd&format=png&color=000000', type: 'stage', subType: 'Plant' },
    { name: 'Fruit Tree', src: 'https://img.icons8.com/?size=100&id=81283&format=png&color=000000', type: 'stage', subType: 'Fruit Tree' },
    { name: 'Large Tree', src: 'https://img.icons8.com/?size=100&id=CqEs6VBkDVHK&format=png&color=000000', type: 'stage', subType: 'Large Tree' },
    { name: 'Acacia Tree', src: 'https://img.icons8.com/?size=100&id=62895&format=png&color=000000', type: 'stage', subType: 'Acacia Tree' },
    { name: 'Delicious Tree', src: 'https://img.icons8.com/?size=100&id=0NIyGX0KTSjk&format=png&color=000000', type: 'stage', subType: 'Delicious Tree' },
    { name: 'EverGreen Tree', src: 'https://img.icons8.com/?size=100&id=HBlx9eXVrlWk&format=png&color=000000', type: 'stage', subType: 'EverGreen Tree' },
    { name: 'Pine Tree', src: 'https://img.icons8.com/?size=100&id=ZMfbShqKmgKm&format=png&color=000000', type: 'stage', subType: 'Pine Tree' },
    { name: 'Cristmas Tree', src: 'https://img.icons8.com/?size=100&id=EAC0p1npPb8v&format=png&color=000000', type: 'stage', subType: 'Cristmas Tree' },
    { name: 'Cristmas Tree1', src: 'https://img.icons8.com/?size=100&id=9jXKB0NN0fzm&format=png&color=000000', type: 'stage', subType: 'Cristmas Tree1' },
    { name: 'Coconut Tree', src: 'https://img.icons8.com/?size=100&id=aD636kZ0lqiR&format=png&color=000000', type: 'stage', subType: 'Coconut Tree' },
    { name: 'Cristmas Tree3', src: 'https://img.icons8.com/?size=100&id=jqYvlDhYkNCW&format=png&color=000000', type: 'stage', subType: 'Cristmas Tree3' },
    { name: 'Black Tree', src: 'https://img.icons8.com/?size=100&id=Mo00dEFcW8L9&format=png&color=000000', type: 'stage', subType: 'Black Tree' },
    { name: 'Willow Tree', src: 'https://img.icons8.com/?size=100&id=65390&format=png&color=000000', type: 'stage', subType: 'Willow Tree' },
    { name: 'Big Tree10', src: 'https://img.icons8.com/?size=100&id=BAyVjKCtHizZ&format=png&color=000000', type: 'stage', subType: 'Big Tree10' },
    { name: 'Deforest', src: 'https://img.icons8.com/?size=100&id=JqFVAM9ZhdqS&format=png&color=000000', type: 'stage', subType: 'Deforest' },
    { name: 'Big Tree', src: 'https://img.icons8.com/?size=100&id=sG0aZdVw65G6&format=png&color=000000', type: 'stage', subType: 'Big Tree' },
    { name: 'Palm Tree', src: 'https://img.icons8.com/?size=100&id=TfV5dh9iiiyQ&format=png&color=000000', type: 'stage', subType: 'Palm Tree' },
    { name: 'Big Tree3', src: 'https://img.icons8.com/?size=100&id=EfS7os8Ri3P6&format=png&color=000000', type: 'stage', subType: 'Big Tree3' },
    { name: 'Sakura Tree', src: 'https://img.icons8.com/?size=100&id=p0J2jC1HbkYT&format=png&color=000000', type: 'stage', subType: 'Sakura Tree' },
    { name: 'Sakura Tree1', src: 'https://img.icons8.com/?size=100&id=fd53fBVXem0Y&format=png&color=000000', type: 'stage', subType: 'Sakura Tree1' },
    { name: 'Palm Tree2', src: 'https://img.icons8.com/?size=100&id=kHmrL9Xwilax&format=png&color=000000', type: 'stage', subType: 'Palm Tree2' },
    { name: 'Oak Tree1', src: 'https://img.icons8.com/?size=100&id=IJqMqWtLKkNz&format=png&color=000000', type: 'stage', subType: 'Oak Tree1' },
    { name: 'Big Tree4', src: 'https://img.icons8.com/?size=100&id=iRkC3lOAlK0o&format=png&color=000000', type: 'stage', subType: 'Big Tree4' },
    { name: 'Big Tree5', src: 'https://img.icons8.com/?size=100&id=bpdeXzYq5Wk8&format=png&color=000000', type: 'stage', subType: 'Big Tree5' },
    { name: 'Big Tree6', src: 'https://img.icons8.com/?size=100&id=wkGQegBIePW5&format=png&color=000000', type: 'stage', subType: 'Big Tree6' },
    { name: 'Dead Tree', src: 'https://img.icons8.com/?size=100&id=PcJuYIbd78nM&format=png&color=000000', type: 'stage', subType: 'Dead Tree' },
    { name: 'Big Tree7', src: 'https://img.icons8.com/?size=100&id=HQ4pxIzDd3EG&format=png&color=000000', type: 'stage', subType: 'Big Tree7' },
    { name: 'Big Tree8', src: 'https://img.icons8.com/?size=100&id=mbZhDYQiwbRD&format=png&color=000000', type: 'stage', subType: 'Big Tree8' },
    { name: 'Big Tree9', src: 'https://img.icons8.com/?size=100&id=LNCVauLfEKjQ&format=png&color=000000', type: 'stage', subType: 'Big Tree9' },
    { name: 'Building-1', src: 'https://img.icons8.com/?size=100&id=J3w76cMS9cUS&format=png&color=000000', type: 'stage', subType: 'Building-1' },
    { name: 'Building-2', src: 'https://img.icons8.com/?size=100&id=IZbdh4a-hOx0&format=png&color=000000', type: 'stage', subType: 'Building-2' },
    { name: 'Building-3', src: 'https://img.icons8.com/?size=100&id=GCh1TrpiWNpH&format=png&color=000000', type: 'stage', subType: 'Building-3' },
    { name: 'Building-4', src: 'https://img.icons8.com/?size=100&id=FrBSkVzw5GE_&format=png&color=000000', type: 'stage', subType: 'Building-4' },
    { name: 'Building-5', src: 'https://img.icons8.com/?size=100&id=30179&format=png&color=000000', type: 'stage', subType: 'Building-5' },
    { name: 'Building-6', src: 'https://img.icons8.com/?size=100&id=103777&format=png&color=000000', type: 'stage', subType: 'Building-6' },
    { name: 'Building-7', src: 'https://img.icons8.com/?size=100&id=hAXS8XqB99HJ&format=png&color=000000', type: 'stage', subType: 'Building-7' },
    { name: 'Building-8', src: 'https://img.icons8.com/?size=100&id=2WLcCor1cHKB&format=png&color=000000', type: 'stage', subType: 'Building-8' },
    { name: 'Building-9', src: 'https://img.icons8.com/?size=100&id=2WLcCor1cHKB&format=png&color=000000', type: 'stage', subType: 'Building-9' },
    { name: 'Building-10', src: 'https://img.icons8.com/?size=100&id=S8Xc31dmCqxr&format=png&color=000000', type: 'stage', subType: 'Building-10' },
    { name: 'Building-11', src: 'https://img.icons8.com/?size=100&id=jW56SCKOWnp_&format=png&color=000000', type: 'stage', subType: 'Building-11' },
    { name: 'Building-12', src: 'https://img.icons8.com/?size=100&id=p8ii741wDy2D&format=png&color=000000', type: 'stage', subType: 'Building-12' },
    { name: 'Building-13', src: 'https://img.icons8.com/?size=100&id=117508&format=png&color=000000', type: 'stage', subType: 'Building-13' },
    { name: 'Skyscraper', src: 'https://img.icons8.com/?size=100&id=BaRVtZj1CRa2&format=png&color=000000', type: 'stage', subType: 'Skyscraper' },
    { name: 'Apartment', src: 'https://img.icons8.com/?size=100&id=bjvkTPQnhQck&format=png&color=000000', type: 'stage', subType: 'Apartment' },
    { name: 'Shop', src: 'https://img.icons8.com/?size=100&id=jjerrupkFYYQ&format=png&color=000000', type: 'stage', subType: 'Shop' },
    { name: 'Hospital', src: 'https://img.icons8.com/?size=100&id=rBh1fuOC6Bjx&format=png&color=000000', type: 'stage', subType: 'Hospital' },
    { name: 'School', src: 'https://img.icons8.com/?size=100&id=RWH5eUW9Vr7f&format=png&color=000000', type: 'stage', subType: 'School' },
    { name: 'Hostel', src: 'https://img.icons8.com/?size=100&id=AVe9YeyAXTql&format=png&color=000000', type: 'stage', subType: 'Hostel' },
    { name: 'Chruch', src: 'https://img.icons8.com/?size=100&id=r7BjSDOMXk8U&format=png&color=000000', type: 'stage', subType: 'Chruch' },
    { name: 'Bank', src: 'https://img.icons8.com/?size=100&id=VbL8v3mm1qyp&format=png&color=000000', type: 'stage', subType: 'Bank' },
    { name: 'Stadium', src: 'https://img.icons8.com/?size=100&id=mFuCgbDlUhK5&format=png&color=000000', type: 'stage', subType: 'Stadium' },
    { name: 'Classical Building', src: 'https://img.icons8.com/?size=100&id=UYjACvthEZ6x&format=png&color=000000', type: 'stage', subType: 'Classical Building' },
    { name: 'Rocket', src: 'https://img.icons8.com/?size=100&id=bY5t0noHcfXn&format=png&color=000000', type: 'stage', subType: 'Rocket' },
    { name: 'Money Bag', src: 'https://img.icons8.com/?size=100&id=JI2bnOlUlrmw&format=png&color=000000', type: 'stage', subType: 'Money Bag' },
    { name: 'Clasic house', src: 'https://img.icons8.com/?size=100&id=EpgbBKipIWng&format=png&color=000000', type: 'stage', subType: 'Clasic House' },
    { name: 'Clasic house1', src: 'https://img.icons8.com/?size=100&id=qPwXqWJTprd8&format=png&color=000000', type: 'stage', subType: 'Clasic house1' },
    { name: 'Modern House', src: 'https://img.icons8.com/?size=100&id=Tz3vhPY11OUO&format=png&color=000000', type: 'stage', subType: 'Modern House' },
    { name: 'Small House', src: 'https://img.icons8.com/?size=100&id=edn4AO8E86gV&format=png&color=000000', type: 'stage', subType: 'Small House' },
    { name: 'Gaint Wheel', src: 'https://img.icons8.com/?size=100&id=GcXOV6oxlohB&format=png&color=000000', type: 'stage', subType: 'Gaint Wheel' },
    { name: 'Roller Coaster', src: 'https://img.icons8.com/?size=100&id=9BUe2chmf4S3&format=png&color=000000', type: 'stage', subType: 'Roller Coaster' },
    { name: 'Circus', src: 'https://img.icons8.com/?size=100&id=tw8cn3ENS9eY&format=png&color=000000', type: 'stage', subType: 'Circus' },
    { name: 'Circus 1', src: 'https://img.icons8.com/?size=100&id=BECyoJ3v33p3&format=png&color=000000', type: 'stage', subType: 'Circus 1' },
    { name: 'WindMill', src: 'https://img.icons8.com/?size=100&id=ZTJkZEiyHPym&format=png&color=000000', type: 'stage', subType: 'Windmill' },
    { name: 'Carousel', src: 'https://img.icons8.com/?size=100&id=20x4v6pp2ZQ7&format=png&color=000000', type: 'stage', subType: 'Carousel' },
    { name: 'Horse Ride', src: 'https://img.icons8.com/?size=100&id=kfh1gaNvfWBM&format=png&color=000000', type: 'stage', subType: 'Horse Ride' },
    { name: 'Temple', src: 'https://img.icons8.com/?size=100&id=eTApPBqmoGMs&format=png&color=000000', type: 'stage', subType: 'Temple' },
    { name: 'Museum', src: 'https://img.icons8.com/?size=100&id=zhEpG5xJmsGa&format=png&color=000000', type: 'stage', subType: 'Museum' },
    { name: 'Architecture', src: 'https://img.icons8.com/?size=100&id=zuynU2HerEB5&format=png&color=000000', type: 'stage', subType: 'Architecture' },
    { name: 'Castel 1', src: 'https://img.icons8.com/?size=100&id=0n5XGPEjXCBo&format=png&color=000000', type: 'stage', subType: 'Castel 1' },
    { name: 'Temple of Heaven', src: 'https://img.icons8.com/?size=100&id=r3sr8v1Zgg17&format=png&color=000000', type: 'stage', subType: 'Temple of Heaven' },
    { name: 'India Gate', src: 'https://img.icons8.com/?size=100&id=r228dM8Gno9h&format=png&color=000000', type: 'stage', subType: 'India Gate' },
    { name: 'Bhurj Khalifa', src: 'https://img.icons8.com/?size=100&id=xuaxePVAVqlg&format=png&color=000000', type: 'stage', subType: 'Bhurj Khalifa' },
    { name: 'Empire state of building', src: 'https://img.icons8.com/?size=100&id=5au6CdtX6EF0&format=png&color=000000', type: 'stage', subType: 'Empire state of building' },
    { name: 'Eiffel Tower', src: 'https://img.icons8.com/?size=100&id=9gfytKtJ7lqC&format=png&color=000000', type: 'stage', subType: 'Eiffel Tower' },
    { name: 'SUV', src: 'https://img.icons8.com/?size=100&id=rtsQcWLB311a&format=png&color=000000', type: 'stage', subType: 'SUV' },
    { name: 'Locomotive', src: 'https://img.icons8.com/?size=100&id=8MpEUZojDaky&format=png&color=000000', type: 'stage', subType: 'Locomotive' },
    { name: 'Sport Car', src: 'https://img.icons8.com/?size=100&id=JmwCY3CR5xjs&format=png&color=000000', type: 'stage', subType: 'Sport Car' },
    { name: 'Limo', src: 'https://img.icons8.com/?size=100&id=FCJbtTbJeZ0j&format=png&color=000000', type: 'stage', subType: 'Limo' },
    { name: 'Truck1', src: 'https://img.icons8.com/?size=100&id=qSTAF5uvla0p&format=png&color=000000', type: 'stage', subType: 'Truck1' },
    { name: 'Vintage Car', src: 'https://img.icons8.com/?size=100&id=5WsifS3EdX7C&format=png&color=000000', type: 'stage', subType: 'Vintage Car' },
    { name: 'Jeep', src: 'https://img.icons8.com/?size=100&id=9nzypUxh0wHF&format=png&color=000000', type: 'stage', subType: 'Jeep' },
    { name: 'Van', src: 'https://img.icons8.com/?size=100&id=s54er6wjHvQn&format=png&color=000000', type: 'stage', subType: 'Van' },
    { name: 'Van2', src: 'https://img.icons8.com/?size=100&id=tUt7bDvLXEHZ&format=png&color=000000', type: 'stage', subType: 'Van2' },
    { name: 'Pick Up', src: 'https://img.icons8.com/?size=100&id=zSkd6mxXHh6G&format=png&color=000000', type: 'stage', subType: 'Pick Up' },
    { name: 'Pick Up2', src: 'https://img.icons8.com/?size=100&id=smeRhiaM5M9R&format=png&color=000000', type: 'stage', subType: 'Pick Up2' },
    { name: 'F1', src: 'https://img.icons8.com/?size=100&id=_jtfUqyZM2Pw&format=png&color=000000', type: 'stage', subType: 'F1' },
    { name: 'Go Cart', src: 'https://img.icons8.com/?size=100&id=15146&format=png&color=000000', type: 'stage', subType: 'Go Cart' },
    { name: 'RoadRoller', src: 'https://img.icons8.com/?size=100&id=dpJdCjL29GYv&format=png&color=000000', type: 'stage', subType: 'RoadRoller' },
    { name: 'ForkLift', src: 'https://img.icons8.com/?size=100&id=26312&format=png&color=000000', type: 'stage', subType: 'ForkLift' },
    { name: 'TowTruck', src: 'https://img.icons8.com/?size=100&id=20865&format=png&color=000000', type: 'stage', subType: 'TowTruck' },
    { name: 'CraneTruck', src: 'https://img.icons8.com/?size=100&id=pxBohtxhGrZ0&format=png&color=000000', type: 'stage', subType: 'CraneTruck' },
    { name: 'Tractor', src: 'https://img.icons8.com/?size=100&id=pL6Zmvm4K7Uk&format=png&color=000000', type: 'stage', subType: 'Tractor' },
    { name: 'Tuktuk', src: 'https://img.icons8.com/?size=100&id=XwQfWMz2eoGM&format=png&color=000000', type: 'stage', subType: 'Tuktuk' },
    { name: 'Golf Car', src: 'https://img.icons8.com/?size=100&id=yccKJwgaAibJ&format=png&color=000000', type: 'stage', subType: 'Golf Car' },
    { name: 'School Bus', src: 'https://img.icons8.com/?size=100&id=yWj5KphyTKep&format=png&color=000000', type: 'stage', subType: 'School Bus' },
    { name: 'Bus', src: 'https://img.icons8.com/?size=100&id=g6kmdywLqlFA&format=png&color=000000', type: 'stage', subType: 'Bus' },
    { name: 'MotorCycle', src: 'https://img.icons8.com/?size=100&id=7kklRIoesjQv&format=png&color=000000', type: 'stage', subType: 'MotorCycle' },
    { name: 'Flying Duck', src: 'https://img.icons8.com/?size=100&id=FpOyqZcrwmP3&format=png&color=000000', type: 'stage', subType: 'Flying Duck' },
    { name: 'Flying Bird', src: 'https://img.icons8.com/?size=100&id=30935&format=png&color=000000', type: 'stage', subType: 'Flying Bird' },
    { name: 'Crow', src: 'https://img.icons8.com/?size=100&id=BrfwNYRnTLls&format=png&color=000000', type: 'stage', subType: 'Crow' },
    { name: 'Pigeon', src: 'https://img.icons8.com/?size=100&id=kYqbEzjS6EBh&format=png&color=000000', type: 'stage', subType: 'Pigeon' },
    { name: 'HummingBird', src: 'https://img.icons8.com/?size=100&id=Nt1D465bTSVD&format=png&color=000000', type: 'stage', subType: 'HummingBird' },
    { name: 'BirdHouse', src: 'https://img.icons8.com/?size=100&id=xXapShTzctaU&format=png&color=000000', type: 'stage', subType: 'BirdHouse' },
    { name: 'SeaGull', src: 'https://img.icons8.com/?size=100&id=nx07uNMHf8b2&format=png&color=000000', type: 'stage', subType: 'SeaGull' },
    { name: 'Swan', src: 'https://img.icons8.com/?size=100&id=D2Re1Sh86I1h&format=png&color=000000', type: 'stage', subType: 'Swan' },
    { name: 'Dolfine', src: 'https://img.icons8.com/?size=100&id=tzDJZjq1VdIA&format=png&color=000000', type: 'stage', subType: 'Dolfin' },
    { name: 'Flamingo', src: 'https://img.icons8.com/?size=100&id=i5mxvmWmuLz7&format=png&color=000000', type: 'stage', subType: 'Flamingo' },
    { name: 'Peacock', src: 'https://img.icons8.com/?size=100&id=0AXz01umKPue&format=png&color=000000', type: 'stage', subType: 'Peacock' },
    { name: 'Crab', src: 'https://img.icons8.com/?size=100&id=iC6xVb8kbVGE&format=png&color=000000', type: 'stage', subType: 'Crab' },
    { name: 'Butterfly', src: 'https://img.icons8.com/?size=100&id=pmiijGGgOR0N&format=png&color=000000', type: 'stage', subType: 'Butterfly' },
    { name: 'Bat', src: 'https://img.icons8.com/?size=100&id=5mD2JRHQvi8_&format=png&color=000000', type: 'stage', subType: 'Bat' },
    { name: 'Leopard', src: 'https://img.icons8.com/?size=100&id=QgSRyNS8nIQN&format=png&color=000000', type: 'stage', subType: 'Leopard' },
    { name: 'T-rex', src: 'https://img.icons8.com/?size=100&id=tIRDXHYPPD9x&format=png&color=000000', type: 'stage', subType: 'T-rex' },
    { name: 'Diplodocus', src: 'https://img.icons8.com/?size=100&id=3F1S65KAeUpP&format=png&color=000000', type: 'stage', subType: 'Diplodocus' },
    { name: 'Spinosaurus', src: 'https://img.icons8.com/?size=100&id=7CbRLyB4ds1O&format=png&color=000000', type: 'stage', subType: 'Spinosaurus' },
    { name: 'Tyrannasaur', src: 'https://img.icons8.com/?size=100&id=M4p3qvRyOoBp&format=png&color=000000', type: 'stage', subType: 'Tyrannasaur' },
    { name: 'Iguana', src: 'https://img.icons8.com/?size=100&id=N2Qk9zdBdgNd&format=png&color=000000', type: 'stage', subType: 'Iguana' },
    { name: 'Chameleon', src: 'https://img.icons8.com/?size=100&id=YuFMb4xh7RMx&format=png&color=000000', type: 'stage', subType: 'Chameleon' },
    { name: 'Ankylosaurus', src: 'https://img.icons8.com/?size=100&id=M4p3qvRyOoBp&format=png&color=000000', type: 'stage', subType: 'Ankylosaurus' },
    { name: 'Stegosaurus', src: 'https://img.icons8.com/?size=100&id=8rPQc6z6RrkL&format=png&color=000000', type: 'stage', subType: 'Stegosaurus' },
    { name: 'Allosaurus', src: 'https://img.icons8.com/?size=100&id=m6LDP9HigWhv&format=png&color=000000', type: 'stage', subType: 'Allosaurus' },
    { name: 'Diloposauras', src: 'https://img.icons8.com/?size=100&id=p7nIPOagI3ZW&format=png&color=000000', type: 'stage', subType: 'Diloposauras' },
    { name: 'Pterodactyl', src: 'https://img.icons8.com/?size=100&id=NUxiToWhP27X&format=png&color=000000', type: 'stage', subType: 'Pterodactyl' },
    { name: 'Elasmosaurus', src: 'https://img.icons8.com/?size=100&id=uZkQ8qzHinb1&format=png&color=000000', type: 'stage', subType: 'Elasmosaurus' },
    { name: 'Brachiosaurus', src: 'https://img.icons8.com/?size=100&id=V3Hf7hGRfwDE&format=png&color=000000', type: 'stage', subType: 'Brachiosaurus' },
    { name: 'Girafe', src: 'https://img.icons8.com/?size=100&id=8HwBNCcJljmG&format=png&color=000000', type: 'stage', subType: 'Girafe' },
    { name: 'Shark', src: 'https://img.icons8.com/?size=100&id=GB0kaLAzScQ8&format=png&color=000000', type: 'stage', subType: 'Shark' },
    { name: 'Hammerhead', src: 'https://img.icons8.com/?size=100&id=ocobZUxC7tcB&format=png&color=000000', type: 'stage', subType: 'Hammerhead' },
    { name: 'Fish', src: 'https://img.icons8.com/?size=100&id=101716&format=png&color=000000', type: 'stage', subType: 'Fish' },
    { name: 'Fish2', src: 'https://img.icons8.com/?size=100&id=16040&format=png&color=000000', type: 'stage', subType: 'Fish2' },
    { name: 'Fish3', src: 'https://img.icons8.com/?size=100&id=OClCFhCarb8m&format=png&color=000000', type: 'stage', subType: 'Fish3' },

    { name: 'Golden Tree', src: 'https://img.icons8.com/?size=100&id=ky0KoGLLmzbn&format=png&color=000000', type: 'stage', subType: 'golden_tree' },
    { name: 'Oak Tree', src: 'https://img.icons8.com/?size=100&id=jD6t-ciF8Wat&format=png&color=000000', type: 'stage', subType: 'oak_tree' },
    { name: 'House', src: 'https://img.icons8.com/?size=100&id=ETkL78XWuDdG&format=png&color=000000', type: 'stage', subType: 'house' },
    { name: 'Scooter', src: 'https://img.icons8.com/?size=100&id=ReOrCrJ4JPIW&format=png&color=000000', type: 'stage', subType: 'scooter' },
    { name: 'Park Bench', src: 'https://img.icons8.com/?size=100&id=CZ9WAJWZl319&format=png&color=000000', type: 'stage', subType: 'bench' },
    { name: 'Small Grass', src: 'https://img.icons8.com/?size=100&id=18052&format=png&color=000000', type: 'stage', subType: 'grass_small' },
    { name: 'Big Grass', src: 'https://img.icons8.com/?size=100&id=IlCuEYosCNfh&format=png&color=000000', type: 'stage', subType: 'grass_big' },
    { name: 'Reeds', src: 'https://img.icons8.com/?size=100&id=hQA0q2YmwOks&format=png&color=000000', type: 'stage', subType: 'reeds' },
    { name: 'Tiny Grass', src: 'https://img.icons8.com/?size=100&id=31706&format=png&color=000000', type: 'stage', subType: 'grass_tiny' },
    { name: 'Plant', src: 'https://img.icons8.com/?size=100&id=80791&format=png&color=000000', type: 'stage', subType: 'plant' },
    { name: 'Man', src: 'https://img.icons8.com/?size=100&id=0I1TXgnS9W0C&format=png&color=000000', type: 'stage', subType: 'man' },
    { name: 'Woman', src: 'https://img.icons8.com/?size=100&id=21833&format=png&color=000000', type: 'stage', subType: 'woman' },
    { name: 'Dog', src: 'https://img.icons8.com/?size=100&id=A99_ArHXykMC&format=png&color=000000', type: 'stage', subType: 'dog' },
    { name: 'Cat', src: 'https://img.icons8.com/?size=100&id=xyUNGNbGr5dN&format=png&color=000000', type: 'stage', subType: 'cat' },
    { name: 'Frog', src: 'https://img.icons8.com/?size=100&id=CZeroXTN10MB&format=png&color=000000', type: 'stage', subType: 'frog' },
    { name: 'Cloudy Moon', src: 'https://img.icons8.com/?size=100&id=64194&format=png&color=000000', type: 'stage', subType: 'moon_cloudy' },
    { name: 'Full Moon', src: 'https://img.icons8.com/?size=100&id=NJx6Gbc4Ng7C&format=png&color=000000', type: 'stage', subType: 'moon_full' },
    { name: 'Sun', src: 'https://img.icons8.com/?size=100&id=8EUmYhfLPTCF&format=png&color=000000', type: 'stage', subType: 'sun' },
    { name: 'Earth', src: 'https://img.icons8.com/?size=100&id=w_qRMJOKoZGs&format=png&color=000000', type: 'stage', subType: 'earth' },
    { name: 'Mars', src: 'https://img.icons8.com/?size=100&id=jUgq2XUL9J5b&format=png&color=000000', type: 'stage', subType: 'mars' },
    { name: 'Jupiter', src: 'https://img.icons8.com/?size=100&id=7BghGgxlhLS2&format=png&color=000000', type: 'stage', subType: 'jupiter' },
    { name: 'Neptune', src: 'https://img.icons8.com/?size=100&id=yqqKbjlxpuv5&format=png&color=000000', type: 'stage', subType: 'neptune' },
    { name: 'Saturn', src: 'https://img.icons8.com/?size=100&id=62038&format=png&color=000000', type: 'stage', subType: 'saturn' },
    { name: 'Uranus', src: 'https://img.icons8.com/?size=100&id=62040&format=png&color=000000', type: 'stage', subType: 'uranus' },
    { name: 'Venus', src: 'https://img.icons8.com/?size=100&id=7BghGgxlhLS2&format=png&color=000000', type: 'stage', subType: 'venus' },
    { name: 'Pluto', src: 'https://img.icons8.com/?size=100&id=62036&format=png&color=000000', type: 'stage', subType: 'pluto' },
    { name: 'Mercury', src: 'https://img.icons8.com/?size=100&id=rGjG7LLzS0Gk&format=png&color=000000', type: 'stage', subType: 'mercury' },
    { name: 'Cloud', src: 'https://img.icons8.com/?size=100&id=21754&format=png&color=000000', type: 'stage', subType: 'cloud' },
    { name: 'Storm Cloud', src: 'https://img.icons8.com/?size=100&id=SpZSUswN9tJs&format=png&color=000000', type: 'stage', subType: 'storm_cloud' },
    { name: 'Rain', src: 'https://img.icons8.com/?size=100&id=RWaaTjQ4JGUu&format=png&color=000000', type: 'stage', subType: 'rain' },
    { name: 'Cloud Rain', src: 'https://img.icons8.com/?size=100&id=KDjKPrgADUUd&format=png&color=000000', type: 'stage', subType: 'cloud_rain' },
    { name: 'Landscape', src: 'https://img.icons8.com/?size=100&id=wRjsixqH27zS&format=png&color=000000', type: 'stage', subType: 'landscape' },
    { name: 'Grand Canyon', src: 'https://img.icons8.com/?size=100&id=SeLr1bn-X2hr&format=png&color=000000', type: 'stage', subType: 'grand_canyon' },
    { name: 'Stone', src: 'https://img.icons8.com/?size=100&id=hCZFwfogHzDa&format=png&color=000000', type: 'stage', subType: 'stone' },
    { name: 'River', src: 'https://img.icons8.com/?size=100&id=17581&format=png&color=000000', type: 'stage', subType: 'river' },
    { name: 'Mountain', src: 'https://img.icons8.com/?size=100&id=81237&format=png&color=000000', type: 'stage', subType: 'mountain' },
    { name: 'Forest Hill', src: 'https://img.icons8.com/?size=100&id=80804&format=png&color=000000', type: 'stage', subType: 'forest_hill' },
    { name: 'Windy Tree', src: 'https://img.icons8.com/?size=100&id=80577&format=png&color=000000', type: 'stage', subType: 'windy_tree' },
    { name: 'Green Dragon', src: 'https://img.icons8.com/?size=100&id=Fg_1mwX-EwWy&format=png&color=000000', type: 'stage', subType: 'dragon_red' },
    { name: 'Ice Wyrm', src: 'https://img.icons8.com/color/512/hydra.png', type: 'stage', subType: 'dragon_sea' },
    { name: 'Distant Pagoda', src: 'https://img.icons8.com/color/512/pagoda.png', type: 'stage', subType: 'pagoda' },
    { name: 'Gothic Castle', src: 'https://img.icons8.com/color/512/castle.png', type: 'stage', subType: 'castle_dark' },
    { name: 'Zoo Outpost', src: 'https://img.icons8.com/color/512/zoo.png', type: 'stage', subType: 'zoo' },
    { name: 'Tidal Sandcastle', src: 'https://img.icons8.com/color/512/sand-castle.png', type: 'stage', subType: 'sandcastle' },
    { name: 'Basket Ball', src: 'https://img.icons8.com/?size=100&id=khlCdbEXD0Sp&format=png&color=000000', type: 'stage', subType: 'basketball' },
    { name: 'Base Ball', src: 'https://img.icons8.com/?size=100&id=K6LVSV4LXNxO&format=png&color=000000', type: 'stage', subType: 'baseball' },
    { name: 'American Football', src: 'https://img.icons8.com/?size=100&id=nVXGpsYrpHNg&format=png&color=000000', type: 'stage', subType: 'american-football' },
    { name: 'Soccer Ball', src: 'https://img.icons8.com/?size=100&id=xsj5Zlx99Bjv&format=png&color=000000', type: 'stage', subType: 'soccer-ball' },
    { name: 'Volly Ball', src: 'https://img.icons8.com/?size=100&id=8Z6VuoMPCLWP&format=png&color=000000', type: 'stage', subType: 'volleyball' },
    { name: 'Tenis Ball', src: 'https://img.icons8.com/?size=100&id=AF2FJWsPaMoY&format=png&color=000000', type: 'stage', subType: 'tennis-ball' },
    { name: 'Rugby Ball', src: 'https://img.icons8.com/?size=100&id=yNU8wMCbR1EW&format=png&color=000000', type: 'stage', subType: 'rugby-ball' },
    { name: 'Watermelon', src: 'https://img.icons8.com/?size=100&id=OtkcjiqPKuyL&format=png&color=000000', type: 'stage', subType: 'watermelon' },
    { name: 'Melon', src: 'https://img.icons8.com/?size=100&id=QwNUTFFipHSw&format=png&color=000000', type: 'stage', subType: 'melon' },
    { name: 'Mango', src: 'https://img.icons8.com/?size=100&id=y06NHH_kl00a&format=png&color=000000', type: 'stage', subType: 'mango' },
    { name: 'Pears', src: 'https://img.icons8.com/?size=100&id=25uh1OZk-hP4&format=png&color=000000', type: 'stage', subType: 'pears' },
    { name: 'PineApple', src: 'https://img.icons8.com/?size=100&id=UVrEwE_pF_Jk&format=png&color=000000', type: 'stage', subType: 'pineapple' },
    { name: 'Tangerine', src: 'https://img.icons8.com/?size=100&id=3MQR_UvgQ9KQ&format=png&color=000000', type: 'stage', subType: 'tangerine' },
    { name: 'Peach', src: 'https://img.icons8.com/?size=100&id=dYvCg4sYEzUU&format=png&color=000000', type: 'stage', subType: 'peach' },
    { name: 'Lemon', src: 'https://img.icons8.com/?size=100&id=YQLIPamA_Xhd&format=png&color=000000', type: 'stage', subType: 'lemon' },
    { name: 'Red Apple', src: 'https://img.icons8.com/?size=100&id=tsGqagtVj0Ka&format=png&color=000000', type: 'stage', subType: 'red-apple' },
    { name: 'Green Apple', src: 'https://img.icons8.com/?size=100&id=LPo-oYep4SZR&format=png&color=000000', type: 'stage', subType: 'green-apple' },
    { name: 'Cherry', src: 'https://img.icons8.com/?size=100&id=HExDs06UMgzs&format=png&color=000000', type: 'stage', subType: 'cherry' },
    { name: 'Grapes', src: 'https://img.icons8.com/?size=100&id=RCFpEF2O1xdZ&format=png&color=000000', type: 'stage', subType: 'grapes' },
    { name: 'Coconut', src: 'https://img.icons8.com/?size=100&id=yfhTKnN2AnGO&format=png&color=000000', type: 'stage', subType: 'coconut' },
    { name: 'Banana', src: 'https://img.icons8.com/?size=100&id=p7YHa8almDEQ&format=png&color=000000', type: 'stage', subType: 'banana' },
    { name: 'Kiwi', src: 'https://img.icons8.com/?size=100&id=dmcVIE1ztYMm&format=png&color=000000', type: 'stage', subType: 'kiwi' },
    { name: 'Strawberry', src: 'https://img.icons8.com/?size=100&id=brWmrA4--NST&format=png&color=000000', type: 'stage', subType: 'strawberry' },
    { name: 'Blueberry', src: 'https://img.icons8.com/?size=100&id=5MIdWtv25ZBe&format=png&color=000000', type: 'stage', subType: 'blueberry' },
    { name: 'Avocado', src: 'https://img.icons8.com/?size=100&id=9Dv8Wi1vh0yp&format=png&color=000000', type: 'stage', subType: 'avocado' },
    { name: 'Bellpaper', src: 'https://img.icons8.com/?size=100&id=HZAeUlLrfvsI&format=png&color=000000', type: 'stage', subType: 'bellpaper' },
    { name: 'Carrot', src: 'https://img.icons8.com/?size=100&id=6f2WYNoYqbXP&format=png&color=000000', type: 'stage', subType: 'carrot' },
    { name: 'Brocolli', src: 'https://img.icons8.com/?size=100&id=uYpGDpQYXpYO&format=png&color=000000', type: 'stage', subType: 'broccoli' },
    { name: 'Tomato', src: 'https://img.icons8.com/?size=100&id=lPmL0NaypRwo&format=png&color=000000', type: 'stage', subType: 'tomato' },
    { name: 'Potato', src: 'https://img.icons8.com/?size=100&id=nFQe1dqlQzLv&format=png&color=000000', type: 'stage', subType: 'potato' },
    { name: 'Hot Paper', src: 'https://img.icons8.com/?size=100&id=kQs5iqwxfvbp&format=png&color=000000', type: 'stage', subType: 'hot-paper' },
    { name: 'Onion', src: 'https://img.icons8.com/?size=100&id=oVuQLxTagzph&format=png&color=000000', type: 'stage', subType: 'onion' },
    { name: 'Corn', src: 'https://img.icons8.com/?size=100&id=8Sli9YJl0SaW&format=png&color=000000', type: 'stage', subType: 'corn' },
    { name: 'EggPlant', src: 'https://img.icons8.com/?size=100&id=DXB2J18f7rfT&format=png&color=000000', type: 'stage', subType: 'eggplant' },
    { name: 'Garlic', src: 'https://img.icons8.com/?size=100&id=D8c2WC1vBJE6&format=png&color=000000', type: 'stage', subType: 'garlic' },
    { name: 'Cucumber', src: 'https://img.icons8.com/?size=100&id=HEUQyzXtODo7&format=png&color=000000', type: 'stage', subType: 'cucumber' },
    { name: 'Bacon', src: 'https://img.icons8.com/?size=100&id=-2CSpVEv0Px2&format=png&color=000000', type: 'stage', subType: 'bacon' },
    { name: 'Meat', src: 'https://img.icons8.com/?size=100&id=hwB2vUsbIvJ2&format=png&color=000000', type: 'stage', subType: 'mean' },
    { name: 'Egg', src: 'https://img.icons8.com/?size=100&id=Ybx2AvxzyUfH&format=png&color=000000', type: 'stage', subType: 'egg' },
    { name: 'Cheese', src: 'https://img.icons8.com/?size=100&id=dOAvFQ4K07oE&format=png&color=000000', type: 'stage', subType: 'cheese' },
    { name: 'Rice', src: 'https://img.icons8.com/?size=100&id=ZcJ13zbLn6Gh&format=png&color=000000', type: 'stage', subType: 'rice' },
    { name: 'Milk', src: 'https://img.icons8.com/?size=100&id=w5z4e-VGlojG&format=png&color=000000', type: 'stage', subType: 'milk' },
    { name: 'Olive', src: 'https://img.icons8.com/?size=100&id=EKRPAtq1mufX&format=png&color=000000', type: 'stage', subType: 'olive' },
    { name: 'Pizza', src: 'https://img.icons8.com/?size=100&id=CYgFsQyxgTod&format=png&color=000000', type: 'stage', subType: 'pizza' },
    { name: 'Hamberger', src: 'https://img.icons8.com/?size=100&id=1itCmhFEiqIW&format=png&color=000000', type: 'stage', subType: 'hamberger' },
    { name: 'French Fries', src: 'https://img.icons8.com/?size=100&id=MSeo0pcLeg0A&format=png&color=000000', type: 'stage', subType: 'french-fries' },
    { name: 'Doughnut', src: 'https://img.icons8.com/?size=100&id=Lp28ZUdhGtAX&format=png&color=000000', type: 'stage', subType: 'doughnut' },
    { name: 'Beans', src: 'https://img.icons8.com/?size=100&id=W7enEEyoySsv&format=png&color=000000', type: 'stage', subType: 'beans' },
    { name: 'Sandwich', src: 'https://img.icons8.com/?size=100&id=HwIEsEmuCUlw&format=png&color=000000', type: 'stage', subType: 'sandwich' },
    { name: 'HotDog', src: 'https://img.icons8.com/?size=100&id=HwIEsEmuCUlw&format=png&color=000000', type: 'stage', subType: 'hotdog' },
    { name: 'Taco', src: 'https://img.icons8.com/?size=100&id=R0Oy1T3-yKJT&format=png&color=000000', type: 'stage', subType: 'taco' },
    { name: 'Pancake', src: 'https://img.icons8.com/?size=100&id=nBX30yPEn6DO&format=png&color=000000', type: 'stage', subType: 'pancake' },
    { name: 'Spaghetti', src: 'https://img.icons8.com/?size=100&id=gPZBYc1Ds8ns&format=png&color=000000', type: 'stage', subType: 'spaghetti' },
    { name: 'Croissant', src: 'https://img.icons8.com/?size=100&id=82vlsBcxQHZ3&format=png&color=000000', type: 'stage', subType: 'croissant' },
    { name: 'ShortCake', src: 'https://img.icons8.com/?size=100&id=DwCtvdHmHOD2&format=png&color=000000', type: 'stage', subType: 'shortcake' },
    { name: 'Cupcake', src: 'https://img.icons8.com/?size=100&id=4mdJMAafisX4&format=png&color=000000', type: 'stage', subType: 'cupcake' },
    { name: 'Waffles', src: 'https://img.icons8.com/?size=100&id=xnXs0CGoBO17&format=png&color=000000', type: 'stage', subType: 'waffles' },
    { name: 'Birthday Cake', src: 'https://img.icons8.com/?size=100&id=O4fphKjTYwZq&format=png&color=000000', type: 'stage', subType: 'birthday-cake' },
    { name: 'Chocolate Bar', src: 'https://img.icons8.com/?size=100&id=vGmusj6T9C1A&format=png&color=000000', type: 'stage', subType: 'chocolate-bar' },
    { name: 'Cookie', src: 'https://img.icons8.com/?size=100&id=Eq5aUzFk6RKG&format=png&color=000000', type: 'stage', subType: 'cookie' },
    { name: 'Pie', src: 'https://img.icons8.com/?size=100&id=oVyWxI4KAabL&format=png&color=000000', type: 'stage', subType: 'pie' },
    { name: 'IceCream', src: 'https://img.icons8.com/?size=100&id=9TNVXg2YE8Dq&format=png&color=000000', type: 'stage', subType: 'icecream' },
    { name: 'Lollipop', src: 'https://img.icons8.com/?size=100&id=t6ZviRvCzSGn&format=png&color=000000', type: 'stage', subType: 'lollipop' },
    { name: 'Coffee', src: 'https://img.icons8.com/?size=100&id=hCiex1L35nUt&format=png&color=000000', type: 'stage', subType: 'coffee' },
    { name: 'Bubble Tea', src: 'https://img.icons8.com/?size=100&id=vt3FjELxZZG0&format=png&color=000000', type: 'stage', subType: 'bubble-tea' },
    { name: 'Candy', src: 'https://img.icons8.com/?size=100&id=SgxB4DXf9dSn&format=png&color=000000', type: 'stage', subType: 'candy' },
    { name: 'IceCream 1', src: 'https://img.icons8.com/?size=100&id=P95mtz9zuqi7&format=png&color=000000', type: 'stage', subType: 'icecream-1' },
    { name: 'Baguette Bread', src: 'https://img.icons8.com/?size=100&id=6sob_vpZVjlM&format=png&color=000000', type: 'stage', subType: 'baguette-bread' },
    { name: 'Green Salad', src: 'https://img.icons8.com/?size=100&id=ovjvLoLpBykl&format=png&color=000000', type: 'stage', subType: 'green-salad' },
    { name: 'Tropical Drink', src: 'https://img.icons8.com/?size=100&id=_4TDTNsyL22A&format=png&color=000000', type: 'stage', subType: 'tropical-drink' },
    { name: 'Shrimp', src: 'https://img.icons8.com/?size=100&id=rm2ULHn0Cvt9&format=png&color=000000', type: 'stage', subType: 'shrimp' },
    { name: 'Fire', src: 'https://img.icons8.com/?size=100&id=QV5JEtrTP6nH&format=png&color=000000', type: 'stage', subType: 'fire' },
    { name: 'Air', src: 'https://img.icons8.com/?size=100&id=dmyNanhX1Hbx&format=png&color=000000', type: 'stage', subType: 'air' },
    { name: 'Water', src: 'https://img.icons8.com/?size=100&id=114622&format=png&color=000000', type: 'stage', subType: 'water' },
    { name: 'Pumpkin', src: 'https://img.icons8.com/?size=100&id=mgwz4yx2TAYq&format=png&color=000000', type: 'stage', subType: 'pumpkin-1' },
    { name: 'Pumpkin 2', src: 'https://img.icons8.com/?size=100&id=JfXxnZq26YLx&format=png&color=000000', type: 'stage', subType: 'pumpkin-2' },
    { name: 'Okra', src: 'https://img.icons8.com/?size=100&id=ilPrCjaFzcxe&format=png&color=000000', type: 'stage', subType: 'okra' },
    { name: 'Deer', src: 'https://img.icons8.com/?size=100&id=mZJZQsQO2XGv&format=png&color=000000', type: 'stage', subType: 'deer' },
    { name: 'Reindeer', src: 'https://img.icons8.com/?size=100&id=Dq1heKO4R8Tz&format=png&color=000000', type: 'stage', subType: 'reindeer' },
    { name: 'Eagle', src: 'https://img.icons8.com/?size=100&id=yb7r2rdbifEu&format=png&color=000000', type: 'stage', subType: 'eagle' },
    { name: 'Scorpion', src: 'https://img.icons8.com/?size=100&id=NvWCpe90wTsp&format=png&color=000000', type: 'stage', subType: 'scorpion' },
    { name: 'Deer 1', src: 'https://img.icons8.com/?size=100&id=wuDWYmxgmGJO&format=png&color=000000', type: 'stage', subType: 'deer-1' },
    { name: 'Bear', src: 'https://img.icons8.com/?size=100&id=qlYqIMUdIBvt&format=png&color=000000', type: 'stage', subType: 'bear' },
    { name: 'Panda', src: 'https://img.icons8.com/?size=100&id=icaN75Fl2Ka2&format=png&color=000000', type: 'stage', subType: 'panda' },
    { name: 'Mammoth', src: 'https://img.icons8.com/?size=100&id=Wvt82pQ691UT&format=png&color=000000', type: 'stage', subType: 'mammoth' },
    { name: 'Mastodon', src: 'https://img.icons8.com/?size=100&id=Nf0omk2TMsHM&format=png&color=000000', type: 'stage', subType: 'mastodon' },
    { name: 'Cow', src: 'https://img.icons8.com/?size=100&id=HEEhn6wh3fuG&format=png&color=000000', type: 'stage', subType: 'cow' },
    { name: 'Pig', src: 'https://img.icons8.com/?size=100&id=hSTeygAnnDEY&format=png&color=000000', type: 'stage', subType: 'pig' },
    { name: 'Goat', src: 'https://img.icons8.com/?size=100&id=9Vq1R4Ls9zI2&format=png&color=000000', type: 'stage', subType: 'goat' },
    { name: 'Crocodile', src: 'https://img.icons8.com/?size=100&id=Rs7WtznR24Af&format=png&color=000000', type: 'stage', subType: 'crocodile' },
    { name: 'Emu', src: 'https://img.icons8.com/?size=100&id=m5yDry729w3f&format=png&color=000000', type: 'stage', subType: 'emu' },
    { name: 'Llama', src: 'https://img.icons8.com/?size=100&id=tzZXfNBcvjcc&format=png&color=000000', type: 'stage', subType: 'llama' },
    { name: 'Chicken', src: 'https://img.icons8.com/?size=100&id=5kU7J5r1PwTt&format=png&color=000000', type: 'stage', subType: 'chicken' },
    { name: 'Zebra', src: 'https://img.icons8.com/?size=100&id=5LKKATi9CVcS&format=png&color=000000', type: 'stage', subType: 'zebra' },
    { name: 'Fox', src: 'https://img.icons8.com/?size=100&id=zZZF3jGvYp4A&format=png&color=000000', type: 'stage', subType: 'fox' },
    { name: 'Cheetah', src: 'https://img.icons8.com/?size=100&id=pUbIfur736Lt&format=png&color=000000', type: 'stage', subType: 'cheetah' },
    { name: 'Wild Boar', src: 'https://img.icons8.com/?size=100&id=2R5IE9H5ssm8&format=png&color=000000', type: 'stage', subType: 'wild-boar' },
    { name: 'Vulture', src: 'https://img.icons8.com/?size=100&id=Ry8UMzPbDNv9&format=png&color=000000', type: 'stage', subType: 'vulture' },
    { name: 'Ostrich', src: 'https://img.icons8.com/?size=100&id=UOOktdYeFkNo&format=png&color=000000', type: 'stage', subType: 'ostrich' },
    { name: 'Hippopotamus', src: 'https://img.icons8.com/?size=100&id=MoJKNn2q4Rom&format=png&color=000000', type: 'stage', subType: 'hippopotamus' },
    { name: 'Peacock', src: 'https://img.icons8.com/?size=100&id=S3wGjKRpyspY&format=png&color=000000', type: 'stage', subType: 'peacock' },
    { name: 'Orangutan', src: 'https://img.icons8.com/?size=100&id=IjAhlH19oj3B&format=png&color=000000', type: 'stage', subType: 'orangutan' },
    { name: 'Television', src: 'https://img.icons8.com/?size=100&id=97c9kYT7GZRT&format=png&color=000000', type: 'stage', subType: 'television' },
    { name: 'Laptop', src: 'https://img.icons8.com/?size=100&id=W71gI8WAwOuF&format=png&color=000000', type: 'stage', subType: 'laptop' },
    { name: 'Office Table', src: 'https://img.icons8.com/?size=100&id=lKznthLupLSM&format=png&color=000000', type: 'stage', subType: 'office-table' },
    { name: 'Monitor', src: 'https://img.icons8.com/?size=100&id=ZQLkIabSAoZW&format=png&color=000000', type: 'stage', subType: 'monitor' },
    { name: 'Radio', src: 'https://img.icons8.com/?size=100&id=5f8NZFNLsz9r&format=png&color=000000', type: 'stage', subType: 'radio' },
    { name: 'Pencil', src: 'https://img.icons8.com/?size=100&id=102333&format=png&color=000000', type: 'stage', subType: 'pencil-1' },
    { name: 'Book', src: 'https://img.icons8.com/?size=100&id=102327&format=png&color=000000', type: 'stage', subType: 'book-1' },
    { name: 'Air Conditioner', src: 'https://img.icons8.com/?size=100&id=wGf7fBcLEZxM&format=png&color=000000', type: 'stage', subType: 'air-conditioner' },
    { name: 'Refrigerator', src: 'https://img.icons8.com/?size=100&id=cPvUGpqA1Dmh&format=png&color=000000', type: 'stage', subType: 'refrigerator' },
    { name: 'Microwave', src: 'https://img.icons8.com/?size=100&id=FpLBVCEWI1yN&format=png&color=000000', type: 'stage', subType: 'microwave' },
    { name: 'Washing Machine', src: 'https://img.icons8.com/?size=100&id=Jvd285hxXqK6&format=png&color=000000', type: 'stage', subType: 'washing-machine' },
    { name: 'Wardrobe', src: 'https://img.icons8.com/?size=100&id=MWaTbvqTOr4b&format=png&color=000000', type: 'stage', subType: 'wardrobe' },
    { name: 'Work Station', src: 'https://img.icons8.com/?size=100&id=Q_GjggrIMm09&format=png&color=000000', type: 'stage', subType: 'work-station' },
    { name: 'Sofa', src: 'https://img.icons8.com/?size=100&id=bDdxkx7b6RDS&format=png&color=000000', type: 'stage', subType: 'sofa' },
    { name: 'Garage', src: 'https://img.icons8.com/?size=100&id=c1CPNKYWx1tX&format=png&color=000000', type: 'stage', subType: 'garage' },
    { name: 'Shirt', src: 'https://img.icons8.com/?size=100&id=mulummlCfSZ6&format=png&color=000000', type: 'stage', subType: 'shirt' },
    { name: 'Jacket', src: 'https://img.icons8.com/?size=100&id=GvfGboYsKv7P&format=png&color=000000', type: 'stage', subType: 'jacket' },
    { name: 'Raincoat', src: 'https://img.icons8.com/?size=100&id=Xj5FO6LnP6Nr&format=png&color=000000', type: 'stage', subType: 'raincoat' },
    { name: 'Mens Hoodie', src: 'https://img.icons8.com/?size=100&id=EUH4ielF00Ni&format=png&color=000000', type: 'stage', subType: 'mens-hoodie' },
    { name: 'Jeans', src: 'https://img.icons8.com/?size=100&id=LKSFx6hblnOz&format=png&color=000000', type: 'stage', subType: 'jeans' },
    { name: 'Coat', src: 'https://img.icons8.com/?size=100&id=mIxsMRAFbS8k&format=png&color=000000', type: 'stage', subType: 'coat' },
    { name: 'Trash', src: 'https://img.icons8.com/?size=100&id=pu2MfAM7qtF0&format=png&color=000000', type: 'stage', subType: 'trash' },
    { name: 'Kitchen', src: 'https://img.icons8.com/?size=100&id=obIHLf6jgIiF&format=png&color=000000', type: 'stage', subType: 'kitchen' },
    { name: 'Bath Tub', src: 'https://img.icons8.com/?size=100&id=318OIBZIBoyw&format=png&color=000000', type: 'stage', subType: 'bath-tub' },
    { name: 'Bed', src: 'https://img.icons8.com/?size=100&id=JF5jAha6Jh4N&format=png&color=000000', type: 'stage', subType: 'bed' },
    { name: 'Aquarium', src: 'https://img.icons8.com/?size=100&id=D-11piArA-4b&format=png&color=000000', type: 'stage', subType: 'aquarium' },
    { name: 'Xylophone', src: 'https://img.icons8.com/?size=100&id=AT8FOxKKYMud&format=png&color=000000', type: 'stage', subType: 'Xylophone' },

    { name: 'Syringe', src: 'https://img.icons8.com/?size=100&id=FXq4D8KeVVd3&format=png&color=000000', type: 'stage', subType: 'syringe' },
    { name: 'Gas Station', src: 'https://img.icons8.com/?size=100&id=Yjf6rB_2MNTp&format=png&color=000000', type: 'stage', subType: 'gas-station' },
    { name: 'Humming Bird', src: 'https://img.icons8.com/?size=100&id=_tOGCvyYkx7s&format=png&color=000000', type: 'stage', subType: 'hummingbird' },
    { name: 'Penguin', src: 'https://img.icons8.com/?size=100&id=101724&format=png&color=000000', type: 'stage', subType: 'penguin' },
    { name: 'Rabit', src: 'https://img.icons8.com/?size=100&id=101690&format=png&color=000000', type: 'stage', subType: 'rabbit-wild' },
    { name: 'Crab', src: 'https://img.icons8.com/?size=100&id=xtp_K8TJSIbw&format=png&color=000000', type: 'stage', subType: 'crab' },
    { name: 'Owl', src: 'https://img.icons8.com/?size=100&id=101719&format=png&color=000000', type: 'stage', subType: 'owl' },
    { name: 'LadyBug', src: 'https://img.icons8.com/?size=100&id=VsJJaEU5kONn&format=png&color=000000', type: 'stage', subType: 'ladybug' },
    { name: 'Grasshopper', src: 'https://img.icons8.com/?size=100&id=sPvvZkF03tGu&format=png&color=000000', type: 'stage', subType: 'grasshopper' },
    { name: 'Bee', src: 'https://img.icons8.com/?size=100&id=101705&format=png&color=000000', type: 'stage', subType: 'bee' },
    { name: 'Butterfly', src: 'https://img.icons8.com/?size=100&id=Le7WNzPAARSs&format=png&color=000000', type: 'stage', subType: 'butterfly' },
    { name: 'Spider', src: 'https://img.icons8.com/?size=100&id=FpNu3i_H7fCc&format=png&color=000000', type: 'stage', subType: 'spider' },
    { name: 'CampFire', src: 'https://img.icons8.com/?size=100&id=iLOt-63q7jv2&format=png&color=000000', type: 'stage', subType: 'campfire' },
    { name: 'Beach Umbrella', src: 'https://img.icons8.com/?size=100&id=68487&format=png&color=000000', type: 'stage', subType: 'beach-umbrella' },
    { name: 'Doll', src: 'https://img.icons8.com/?size=100&id=6jRggExVuyFp&format=png&color=000000', type: 'stage', subType: 'doll' },
    { name: 'Barbie Doll', src: 'https://img.icons8.com/?size=100&id=h2NVjov7JSvp&format=png&color=000000', type: 'stage', subType: 'barbie-doll' },
    { name: 'Cockroach', src: 'https://img.icons8.com/?size=100&id=atdDm3Uhs1sX&format=png&color=000000', type: 'stage', subType: 'cockroach' },
    { name: 'Cricket', src: 'https://img.icons8.com/?size=100&id=6MieifgmI1ZO&format=png&color=000000', type: 'stage', subType: 'cricket' },
    { name: 'Flea', src: 'https://img.icons8.com/?size=100&id=qsBTvT45VX5e&format=png&color=000000', type: 'stage', subType: 'flea' },
    { name: 'Vermin', src: 'https://img.icons8.com/?size=100&id=m5YSN3cRhjOx&format=png&color=000000', type: 'stage', subType: 'vermin' },
    { name: 'Omaspides', src: 'https://img.icons8.com/?size=100&id=rKOc1H5HNCr5&format=png&color=000000', type: 'stage', subType: 'omaspides' },
    { name: 'Fly', src: 'https://img.icons8.com/?size=100&id=A17pFjZU35GI&format=png&color=000000', type: 'stage', subType: 'fly' },
    { name: 'BadBug', src: 'https://img.icons8.com/?size=100&id=lr6EAXZpxe1K&format=png&color=000000', type: 'stage', subType: 'badbug' },
    { name: 'Sting Bug', src: 'https://img.icons8.com/?size=100&id=Z2bL8fFuLGkT&format=png&color=000000', type: 'stage', subType: 'stingbug' },
    { name: 'BushMaster Snake', src: 'https://img.icons8.com/?size=100&id=jcEQ02gYPIl1&format=png&color=000000', type: 'stage', subType: 'bushmaster' },
    { name: 'Anaconda', src: 'https://img.icons8.com/?size=100&id=a1yR50Jgsw5W&format=png&color=000000', type: 'stage', subType: 'anaconda' },
    { name: 'Cobra', src: 'https://img.icons8.com/?size=100&id=D06GGpVSEQfu&format=png&color=000000', type: 'stage', subType: 'cobra' },
    { name: 'Rattle Snake', src: 'https://img.icons8.com/?size=100&id=r6qRtS3cEK-X&format=png&color=000000', type: 'stage', subType: 'rattlesnake' },
    { name: 'Sea Turtle', src: 'https://img.icons8.com/?size=100&id=Cmmu3WGTazC4&format=png&color=000000', type: 'stage', subType: 'sea-turtle' },
    { name: 'Turtle', src: 'https://img.icons8.com/?size=100&id=XV81UEe78HVP&format=png&color=000000', type: 'stage', subType: 'turtle' },
    { name: 'Ship', src: 'https://img.icons8.com/?size=100&id=80675&format=png&color=000000', type: 'stage', subType: 'ship' },
    { name: 'Sail Boat', src: 'https://img.icons8.com/?size=100&id=81059&format=png&color=000000', type: 'stage', subType: 'sail-boat' },
    { name: 'Surfing', src: 'https://img.icons8.com/?size=100&id=g8IkRDYggv2J&format=png&color=000000', type: 'stage', subType: 'surfing' },
    { name: 'Boat', src: 'https://img.icons8.com/?size=100&id=I4i1wEKnQdaE&format=png&color=000000', type: 'stage', subType: 'boat' },
    { name: 'Boat 2', src: 'https://img.icons8.com/?size=100&id=TeyeA8DVBBkm&format=png&color=000000', type: 'stage', subType: 'boat-2' },
    { name: 'Fishing Boat', src: 'https://img.icons8.com/?size=100&id=f91LkjHZyCxm&format=png&color=000000', type: 'stage', subType: 'fishing-boat' },
    { name: 'Scuba Diving', src: 'https://img.icons8.com/?size=100&id=31911&format=png&color=000000', type: 'stage', subType: 'scuba-diving' },
    { name: 'Sun Lounger', src: 'https://img.icons8.com/?size=100&id=Hd8soezFFtye&format=png&color=000000', type: 'stage', subType: 'sun-lounger' },
    { name: 'Woman Sunbathing', src: 'https://img.icons8.com/?size=100&id=pieindZZtoKH&format=png&color=000000', type: 'stage', subType: 'woman-sunbathing' },
    { name: 'Man Sunbathing', src: 'https://img.icons8.com/?size=100&id=31928&format=png&color=000000', type: 'stage', subType: 'man-sunbathing' },
    { name: 'Recliner', src: 'https://img.icons8.com/?size=100&id=4kA968YnHnr8&format=png&color=000000', type: 'stage', subType: 'recliner' },
    { name: 'SunBed', src: 'https://img.icons8.com/?size=100&id=dH3ZzW7Y3l9x&format=png&color=000000', type: 'stage', subType: 'sunbed' },
    { name: 'Beach Chair', src: 'https://img.icons8.com/?size=100&id=5YJZeCXwNdYF&format=png&color=000000', type: 'stage', subType: 'beach-chair' },
    { name: 'Cycling', src: 'https://img.icons8.com/?size=100&id=JcaYpWCChJdb&format=png&color=000000', type: 'stage', subType: 'cycling' },
    { name: 'Biking', src: 'https://img.icons8.com/?size=100&id=ITgKZ3xjWphi&format=png&color=000000', type: 'stage', subType: 'biking' },
    { name: 'Horse Riding', src: 'https://img.icons8.com/?size=100&id=LuhFumPGCq9L&format=png&color=000000', type: 'stage', subType: 'horse-riding' },
    { name: 'Swimming', src: 'https://img.icons8.com/?size=100&id=mKLcKNJXJamh&format=png&color=000000', type: 'stage', subType: 'swimming' },
    { name: 'Man bouncing Ball', src: 'https://img.icons8.com/?size=100&id=t5lSKGAZ80E3&format=png&color=000000', type: 'stage', subType: 'man-bouncing-ball' },
    { name: 'woman playing Handball', src: 'https://img.icons8.com/?size=100&id=1yeWsFuaybi9&format=png&color=000000', type: 'stage', subType: 'woman-playing-handball' },
    { name: 'woman Running', src: 'https://img.icons8.com/?size=100&id=7Z4KsV63DACh&format=png&color=000000', type: 'stage', subType: 'woman-running' },
    { name: 'Man Running', src: 'https://img.icons8.com/?size=100&id=WESS8gdHMgLA&format=png&color=000000', type: 'stage', subType: 'man-running' },
    { name: 'Man Walking', src: 'https://img.icons8.com/?size=100&id=6WcAhZYn3BDV&format=png&color=000000', type: 'stage', subType: 'man-walking' },
    { name: 'Woman Walking', src: 'https://img.icons8.com/?size=100&id=6ujTSZ4zM5QN&format=png&color=000000', type: 'stage', subType: 'woman-walking' },
    { name: 'Person Golfing', src: 'https://img.icons8.com/?size=100&id=eZBdUuW3frUK&format=png&color=000000', type: 'stage', subType: 'person-golfing' },
    { name: 'Power Lifting', src: 'https://img.icons8.com/?size=100&id=Q79hFrrKroIT&format=png&color=000000', type: 'stage', subType: 'power-lifting' },
    { name: 'Skier', src: 'https://img.icons8.com/?size=100&id=oqrXK826OcgX&format=png&color=000000', type: 'stage', subType: 'skier' },
    { name: 'Snowboarding', src: 'https://img.icons8.com/?size=100&id=2ZP3nwckax4G&format=png&color=000000', type: 'stage', subType: 'snowboarding' },
    { name: 'Man Surfing', src: 'https://img.icons8.com/?size=100&id=jvctCRh6VNsA&format=png&color=000000', type: 'stage', subType: 'man-surfing' },
    { name: 'Man Dancing', src: 'https://img.icons8.com/?size=100&id=sJB3Bs9nv2lt&format=png&color=000000', type: 'stage', subType: 'man-dancing' },
    { name: 'Woman Dancing', src: 'https://img.icons8.com/?size=100&id=ldVm2i9JXRvS&format=png&color=000000', type: 'stage', subType: 'woman-dancing' },
    { name: 'Woman Meditating', src: 'https://img.icons8.com/?size=100&id=hYBKkWFjtuCu&format=png&color=000000', type: 'stage', subType: 'woman-meditating' },
    { name: 'Man Meditating', src: 'https://img.icons8.com/?size=100&id=WFSwkOenGPSn&format=png&color=000000', type: 'stage', subType: 'man-meditating' },
    { name: 'Man and Woman', src: 'https://img.icons8.com/?size=100&id=ir8cP5Ls2tr6&format=png&color=000000', type: 'stage', subType: 'man-and-woman' },
    { name: 'Wheel Chair', src: 'https://img.icons8.com/?size=100&id=fTqkYxBkg1Gw&format=png&color=000000', type: 'stage', subType: 'wheel-chair' },
    { name: 'Man Cartwheeling', src: 'https://img.icons8.com/?size=100&id=6qmKe8iuY7R2&format=png&color=000000', type: 'stage', subType: 'man-cartwheeling' },
    { name: 'Tracking', src: 'https://img.icons8.com/?size=100&id=dGDjnV2xVCDr&format=png&color=000000', type: 'stage', subType: 'tracking' },
    { name: 'Sibling', src: 'https://img.icons8.com/?size=100&id=LEku1jZSthKW&format=png&color=000000', type: 'stage', subType: 'sibling' },
    { name: 'Family', src: 'https://img.icons8.com/?size=100&id=Q0xNqzei5zcy&format=png&color=000000', type: 'stage', subType: 'family' },
    { name: 'Family 2', src: 'https://img.icons8.com/?size=100&id=KlV03IdxAGz9&format=png&color=000000', type: 'stage', subType: 'family-2' },
    { name: 'Police Station', src: 'https://img.icons8.com/?size=100&id=juJ5xbD4GlSI&format=png&color=000000', type: 'stage', subType: 'police-station' },
    { name: 'PoliceMan', src: 'https://img.icons8.com/?size=100&id=wmabRLqWZSyW&format=png&color=000000', type: 'stage', subType: 'policeman' },
  
    { name: 'Plane', src: 'https://img.icons8.com/?size=100&id=HBosBP8N46Cw&format=png&color=000000', type: 'stage', subType: 'Plane' },
    { name: 'Tank', src: 'https://img.icons8.com/?size=100&id=xPDXxIwbSBec&format=png&color=000000', type: 'stage', subType: 'Tank' },  
    { name: 'Tank 1', src: 'https://img.icons8.com/?size=100&id=xPDXxIwbSBec&format=png&color=000000', type: 'stage', subType: 'Tank 1' }, 
    { name: 'Tank 2', src: 'https://img.icons8.com/?size=100&id=7rzts2yqxihz&format=png&color=000000', type: 'stage', subType: 'Tank 2' },
    { name: 'Tank 3', src: 'https://img.icons8.com/?size=100&id=xPDXxIwbSBec&format=png&color=000000', type: 'stage', subType: 'Tank 3' },
    { name: 'Military Truck', src: 'https://img.icons8.com/?size=100&id=xPDXxIwbSBec&format=png&color=000000', type: 'stage', subType: 'Military Truck' },
    { name: 'Missile Truck', src: 'https://img.icons8.com/?size=100&id=YZRcggF5sppd&format=png&color=000000', type: 'stage', subType: 'Missile Truck' },
    { name: 'Radar Truck', src: 'https://img.icons8.com/?size=100&id=Upqjlx8tfuCy&format=png&color=000000', type: 'stage', subType: 'Radar Truck' },
    { name: 'Military Truck 1', src: 'https://img.icons8.com/?size=100&id=3XgVU6ShXhON&format=png&color=000000', type: 'stage', subType: 'Military Truck 1' },
    { name: 'Military Jeep', src: 'https://img.icons8.com/?size=100&id=dGIYGgYMOW3g&format=png&color=000000', type: 'stage', subType: 'Military Jeep' },
    { name: 'Military Vehicle', src: 'https://img.icons8.com/?size=100&id=BBPr6XLyn4ow&format=png&color=000000', type: 'stage', subType: 'Military Vehicle' },
    { name: 'Amphibious', src: 'https://img.icons8.com/?size=100&id=R3bD0q9Fdt95&format=png&color=000000', type: 'stage', subType: 'Amphibious' },
    { name: 'Missile', src: 'https://img.icons8.com/?size=100&id=YZRcggF5sppd&format=png&color=000000', type: 'stage', subType: 'Missile' },
    { name: 'Jet 1', src: 'https://img.icons8.com/?size=100&id=XRrGocZI5lJ6&format=png&color=000000', type: 'stage', subType: 'Jet 1' },
    { name: 'Jet 2', src: 'https://img.icons8.com/?size=100&id=PSy8cmL8dg8H&format=png&color=000000', type: 'stage', subType: 'Jet 2' },
    { name: 'Military Plane', src: 'https://img.icons8.com/?size=100&id=Z7MXXXdECvkC&format=png&color=000000', type: 'stage', subType: 'Military Plane' },
    { name: 'Jet 3', src: 'https://img.icons8.com/?size=100&id=hzdkeBvTsJMx&format=png&color=000000', type: 'stage', subType: 'Jet 3' },
    { name: 'Helicopter', src: 'https://img.icons8.com/?size=100&id=xQr0cGL5A0Kr&format=png&color=000000', type: 'stage', subType: 'Helicopter' },
    { name: 'Small Plane', src: 'https://img.icons8.com/?size=100&id=H0vyGejA2WFt&format=png&color=000000', type: 'stage', subType: 'Small Plane' },
    { name: 'Helicopter 2', src: 'https://img.icons8.com/?size=100&id=rkZW4D6oyaCw&format=png&color=000000', type: 'stage', subType: 'Helicopter 2' },
    { name: 'Machine Gun', src: 'https://img.icons8.com/?size=100&id=nl9GYW47JudZ&format=png&color=000000', type: 'stage', subType: 'Machine Gun' },
    { name: 'Machine Gun 2', src: 'https://img.icons8.com/?size=100&id=dV6jDzZuGXpm&format=png&color=000000', type: 'stage', subType: 'Machine Gun 2' },
    { name: 'Rifle', src: 'https://img.icons8.com/?size=100&id=1hREEWjwvYoZ&format=png&color=000000', type: 'stage', subType: 'Rifle' },
    { name: 'Pistol', src: 'https://img.icons8.com/?size=100&id=4aJr7fp5A07v&format=png&color=000000', type: 'stage', subType: 'Pistol' },
    { name: 'Rifle 1', src: 'https://img.icons8.com/?size=100&id=EFOE3lOZvVq4&format=png&color=000000', type: 'stage', subType: 'Rifle 1' },
    { name: 'Radar', src: 'https://img.icons8.com/?size=100&id=CNJFsNbElo63&format=png&color=000000', type: 'stage', subType: 'Radar' },
    { name: 'Radar 2', src: 'https://img.icons8.com/?size=100&id=NkX2DLO7ATck&format=png&color=000000', type: 'stage', subType: 'Radar 2' },
    { name: 'Antena', src: 'https://img.icons8.com/?size=100&id=SHYMAehqJN1p&format=png&color=000000', type: 'stage', subType: 'Antena' },
    

    
  
  
  ],
};

export const MAP_TEMPLATES = [ 
  {name: 'Blank Canvas', url: '' }, 
  {name: 'Beach', url: 'https://i.postimg.cc/N0G656Hp/Beach.png' }, 
  {name: 'Green Hills-2', url: 'https://i.postimg.cc/tTtsVbvz/River-Hill2.png' }, 
  { name: 'Green Hills-1', url: 'https://i.postimg.cc/BvFL4HxM/Green-Hill.jpg' }, 
  { name: 'Night', url: 'https://i.postimg.cc/yx1kmG25/night.jpg' }, 
  { name: 'Valley-1', url: 'https://i.postimg.cc/zfCRz5Cr/Valley-4.jpg' },
  { name: 'City-1', url: 'https://i.postimg.cc/bvx2y8xc/City.jpg' },
  { name: 'HighWay-1', url: 'https://i.postimg.cc/DzrbvFrZ/Highway-1.jpg' },
  { name: 'Desert', url: 'https://i.postimg.cc/mrYFLRQK/Desert.png' },
  { name: 'Green Hills', url: 'https://i.postimg.cc/vBL46y2c/River-Hill.png' },
  { name: 'Valley-3', url: 'https://i.postimg.cc/N06rsY1n/Valley-3.jpg' },
  { name: 'Green Landscape', url: 'https://i.postimg.cc/9fdqmVGS/Valley-1.jpg' },
  { name: 'Pirate Island Quest', url: pirateImg },
  { name: 'Road', url: 'https://i.postimg.cc/hGL7DgLD/Road.jpg' },
  { name: 'Snow Realm', url: 'https://i.postimg.cc/N06rsY1J/Snow-Land.png' },
  { name: 'Desert Oasis', url: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?auto=format&fit=crop&q=80&w=1000' },
];

export const BOARD_SHAPES = [
  { name: 'Rectangle', icon: <Square className="w-8 h-8" /> },
  { name: 'Circle', icon: <Circle className="w-8 h-8" /> },
  { name: 'Triangle', icon: <Triangle className="w-8 h-8" /> },
  { name: 'Diamond', icon: <Diamond className="w-8 h-8" /> },
  { name: 'Pentagon', icon: <Pentagon className="w-8 h-8" /> },
  { name: 'Octagon', icon: <Octagon className="w-8 h-8" /> },
  { name: 'Oval', icon: (
      <svg className="w-8 h-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <ellipse cx="12" cy="12" rx="10" ry="6" />
      </svg>
    ) 
  },
  { name: 'Star', icon: <Star className="w-8 h-8" /> },
];
